apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecards-api
  labels:
    app: kubecards-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecards-api
  template:
    metadata:
      labels:
        app: kubecards-api
    spec:
      containers:
      - name: kubecards-api
        image: kubecards-api:v1
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
